version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: chess-tracker-integration-tests
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tests
