import React from "react"
import { Rubik } from "next/font/google"

import "./globals.css"
import TRPCProvider from "@/app/_providers/TRPCProvider"
import NextAuthProvider from "@/app/_providers/NextAuthProvider"
import ChakraProvider from "@/app/_providers/ChakraProvider"

const rubik = Rubik({
    subsets: ["latin"],
    variable: "--font-rubik",
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={ rubik.className }>
                <main>
                    <TRPCProvider>
                        <NextAuthProvider>
                            <ChakraProvider>
                                { children }
                            </ChakraProvider>
                        </NextAuthProvider>
                    </TRPCProvider>
                </main>
            </body>
        </html>
    )
}
