import React from "react"
import { Inter } from "next/font/google"

import "./globals.css"
import TRPCProvider from "@/app/_providers/TRPCProvider"
import NextAuthProvider from "@/app/_providers/NextAuthProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    <TRPCProvider>
                        <NextAuthProvider>
                            { children }
                        </NextAuthProvider>
                    </TRPCProvider>
                </main>
            </body>
        </html>
    )
}
